#include<stdio.h>
#include<string.h>
#include<sys/resource.h>
#include<sys/time.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<signal.h>
#include<termios.h>
#include<stdarg.h>
#include<unistd.h>
#include<stdlib.h>
#include<sys/wait.h>
#include"xftoa.c"
#include"xatof.c"
#include"itoa.c"
#include<sys/types.h>
#include<sys/stat.h>
#include<sys/time.h>
#include<utime.h>
#include<dirent.h>

