#include<stdio.h>
#include<string.h>
#include<sys/resource.h>
#include<sys/time.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<signal.h>
#include<termios.h>
#include<stdarg.h>
#include<unistd.h>
#include<stdlib.h>
#include<sys/wait.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<sys/time.h>
#include<utime.h>
#include<time.h>
#include<dirent.h>
#include<fcntl.h>
#include<pwd.h>
#include<grp.h>
#include<sys/ipc.h>
#include<sys/msg.h>
#include<sys/timeb.h>
#include<sys/shm.h>
#include<strings.h>
#include<pthread.h>
#include<sched.h>
